import 'expose-loader?$!expose-loader?jQuery!jquery'
import 'bootstrap'
import 'jquery-slimscroll'
import 'jquery-ui/ui/widgets/sortable.js'
import 'jquery-ui/ui/widgets/datepicker.js'
import 'jquery-ui/themes/base/datepicker.css'
import 'admin-lte'
