import routes from '../component/';

export default {
	path: '/system',
	name: '系统管理',
	icon: 'fa fa-gears',
	redirect: '/system/account',
	component: routes.Home,
	children: [{
		path: 'account',
		name: '系统账号管理',
		icon: 'fa fa-user',
		component: routes.ContentWrap,
		redirect: '/system/account/unit',
		children: [{
			path: 'unit',
			name: '用户单位信息管理',
			component: routes.Modules.ViewDetail
		}, {
			path: 'user',
			name: '用户信息管理',
			component: routes.Modules.MessageBox
		}, {
			path: 'proxy',
			name: '角色权限管理',
			component: routes.Modules.Notification
		}, {
			path: 'menu',
			name: '菜单管理',
			component: routes.Modules.MessageBox
		}, {
			path: 'resource',
			name: '资源管理',
			component: routes.Modules.Notification
		}, {
			path: 'element',
			name: '页面元素管理',
			component: routes.Modules.Notification
		}]
	}, {
		path: 'maintenance',
		name: '系统维护',
		icon: 'fa fa-wrench',
		component: routes.ContentWrap,
		redirect: '/system/maintenance/parameter',
		children: [{
			path: 'parameter',
			name: '系统参数配置',
			component: routes.Modules.Message
		}, {
			path: 'reptile',
			name: '爬虫任务管理',
			component: routes.Modules.MessageBox
		}, {
			path: 'monitor-switch',
			name: '企业基础数据监测开关',
			component: routes.Modules.Notification
		}, {
			path: 'dictionary',
			name: '数据字典',
			component: routes.Modules.MessageBox
		}, {
			path: 'cache',
			name: '缓存数据',
			component: routes.Modules.Notification
		}, {
			path: 'wide-domain',
			name: '泛域名维护',
			component: routes.Modules.MessageBox
		}, {
			path: 'register',
			name: '域名注册商',
			component: routes.Modules.Notification
		}, {
			path: 'register-proxy',
			name: '域名注册商接口配置',
			component: routes.Modules.MessageBox
		}, {
			path: 'keyword',
			name: '未备案关键字配置',
			component: routes.Modules.Notification
		}, {
			path: 'website-name',
			name: '排名网站名称自定义',
			component: routes.Modules.MessageBox
		}, {
			path: 'name-filter',
			name: '网站排名过滤',
			component: routes.Modules.Notification
		}]
	}, {
		path: 'log',
		name: '系统日志',
		icon: 'fa fa-file',
		component: routes.ContentWrap,
		redirect: '/system/log/log-management',
		children: [{
			path: 'log-management',
			name: '操作日志管理',
			component: routes.Modules.Message
		}, {
			path: 'analyze-log',
			name: '信安上报数据解析日志',
			component: routes.Modules.MessageBox
		}, {
			path: 'ISMS-log',
			name: 'ISMS数据字典发布日志',
			component: routes.Modules.Notification
		}, {
			path: 'method-dictionary',
			name: '控制类方法字典',
			component: routes.Modules.Message
		}]
	}, {
		path: 'management',
		name: '系统管理',
		icon: 'fa fa-gear',
		component: routes.ContentWrap,
		redirect: '/system/management/userinfo',
		children: [{
			path: 'userinfo',
			name: '用户管理',
			component: routes.Modules.Message
		}, {
			path: 'modules',
			name: '模块管理',
			component: routes.Modules.Message
		}]
	}, {
		path: 'dictionary-management',
		name: '数据字典管理',
		icon: 'fa fa-file-text',
		component: routes.ContentWrap,
		redirect: '/system/dictionary-management/ISMS',
		children: [{
			path: 'ISMS',
			name: 'ISMS数据字典管理',
			component: routes.Modules.MessageBox
		}, {
			path: 'daily',
			name: '日常监测违规类型管理',
			component: routes.Modules.Message
		}, {
			path: 'keyword',
			name: '违法关键词库管理',
			component: routes.Modules.Notification
		}]
	}, {
		path: 'work-status',
		name: '采集运行状态管理',
		icon: 'fa fa-hourglass-end',
		component: routes.ContentWrap,
		redirect: '/system/work-status/DNS-probe',
		children: [{
			path: 'DNS-probe',
			name: 'DNS探针管理',
			component: routes.Modules.Message
		}, {
			path: 'DNS-strategy',
			name: 'DNS策略管理',
			component: routes.Modules.MessageBox
		}, {
			path: 'probe',
			name: '探针状态',
			component: routes.Modules.Notification
		}, {
			path: 'center-status',
			name: '中心端状态',
			component: routes.Modules.Message
		}, {
			path: 'center-detail',
			name: '中心端详情',
			component: routes.Modules.Message
		}, {
			path: 'probe-history',
			name: '探针历史数据',
			component: routes.Modules.MessageBox
		}, {
			path: 'center-history',
			name: '中心端历史数据',
			component: routes.Modules.Notification
		}]
	}, {
		path: 'largescreen',
		name: '大屏节点维护',
		icon: 'fa fa-tv',
		component: routes.ContentWrap,
		redirect: '/system/largescreen/IDC-enterprise',
		children: [{
			path: 'IDC-enterprise',
			name: 'IDC机房节点维护（企业型）',
			component: routes.Modules.Message
		}, {
			path: 'DNS-node',
			name: 'DNS探针节点维护',
			component: routes.Modules.MessageBox
		}, {
			path: 'IDC-resource',
			name: 'IDC机房节点维护（资源型）',
			component: routes.Modules.Notification
		}, {
			path: 'DNS-control',
			name: 'DNS解析控制节点维护',
			component: routes.Modules.Message
		}, {
			path: 'center-detail',
			name: '增值电信业务企业节点维护',
			component: routes.Modules.Message
		}, {
			path: 'screen-control',
			name: '大屏管控指令管理',
			component: routes.Modules.MessageBox
		}, {
			path: 'screen-monitor',
			name: '大屏监测指令维护',
			component: routes.Modules.Notification
		}]
	}, {
		path: 'website-classify',
		name: '网站分类',
		icon: 'fa fa-internet-explorer',
		component: routes.ContentWrap,
		redirect: '/system/website-classify/classify-maintain',
		children: [{
			path: 'classify-maintain',
			name: '分类维护',
			component: routes.Modules.MessageBox
		}]
	}, {
		path: 'work-status',
		name: '系统运行状态',
		icon: 'fa fa-magnet',
		component: routes.ContentWrap,
		redirect: '/system/work-status/ISMS-query',
		children: [{
			path: 'ISMS-query',
			name: 'ISMS运行信安指令查询',
			component: routes.Modules.Message
		}, {
			path: 'ISMS-status',
			name: 'ISMS活动状态',
			component: routes.Modules.MessageBox
		}, {
			path: 'fault',
			name: '故障监测',
			component: routes.Modules.Notification
		}, {
			path: 'DNS',
			name: 'DNS探针运行状态',
			component: routes.Modules.Message
		}, {
			path: 'activity',
			name: '活跃资源上报监测',
			component: routes.Modules.MessageBox
		}, {
			path: 'ACK',
			name: 'ACK状态检测',
			component: routes.Modules.Notification
		}]
	}, {
		path: 'communication-tools',
		name: '通信工具',
		icon: 'fa fa-mobile',
		component: routes.ContentWrap,
		redirect: '/system/communication-tools/message',
		children: [{
			path: 'message',
			name: '短信发送',
			component: routes.Modules.Message
		}, {
			path: 'content',
			name: '短信内容配置',
			component: routes.Modules.MessageBox
		}, {
			path: 'contacts',
			name: '联系人管理',
			component: routes.Modules.Notification
		}, {
			path: 'email',
			name: '邮件发送',
			component: routes.Modules.Message
		}, {
			path: 'message-notify',
			name: '短信通知配置',
			component: routes.Modules.MessageBox
		}]
	}, {
		path: 'information-security',
		name: '信安业务管理',
		icon: 'fa fa-briefcase',
		component: routes.ContentWrap,
		redirect: '/system/information-security/management',
		children: [{
			path: 'management',
			name: '信安业务管理',
			component: routes.Modules.MessageBox
		}]
	}]
}